spring:
  datasource:
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:///integration-tests-db
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    org.springframework.web: info
    org.hibernate: info
    com.home.task: debug