spring:
  flyway:
    baselineOnMigrate: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pWd123$
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 120000
      connectionTimeout: 300000
      leakDetectionThreshold: 300000
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  batch:
    jdbc:
      initialize-schema: "always"
      isolation-level-for-create: READ_COMMITTED

server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    org.springframework.web: debug
    org.hibernate: info
    com.home.task: debug
