spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
