CREATE TABLE if not exists "INT_LOCK"
(
    "LOCK_KEY"     VARCHAR(36),
    "REGION"       VARCHAR(100),
    "CLIENT_ID"    VARCHAR(36),
    "CREATED_DATE" TIMESTAMP NOT NULL,
    PRIMARY KEY ("LOCK_KEY", "REGION")
);
