CREATE TABLE "INT_LOCK"
(
    "LOCK_KEY"     VARCHAR2(36),
    "REGION"       VARCHAR2(100),
    "CLIENT_ID"    VARCHAR2(36),
    "CREATED_DATE" TIMESTAMP NOT NULL,
    PRIMARY KEY ("LOCK_KEY", "REGION")
);
